# Generated by Django 5.1.4 on 2025-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
