# Generated by Django 5.1.4 on 2025-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_galeria_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='titulo',
            field=models.CharField(default='', max_length=150),
        ),
    ]
