# Generated by Django 5.1.5 on 2025-01-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='fotografias/'),
        ),
    ]
