# Generated by Django 5.1.4 on 2025-06-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_galeria_alter_carrera_modalidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
