# Generated by Django 5.1.4 on 2025-06-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_delete_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(max_length=9),
        ),
    ]
